// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC-Ousti2_JGmiCVNRQXs4pqU1CA6aumE',
    appId: '1:105671027225:web:65c10b5a4aba2f37675888',
    messagingSenderId: '105671027225',
    projectId: 'resume-4e9cc',
    authDomain: 'resume-4e9cc.firebaseapp.com',
    storageBucket: 'resume-4e9cc.firebasestorage.app',
    measurementId: 'G-QG23PGJ7HZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcM8qPOLbQmiS43S4nuHCgfh-zTMhgOX8',
    appId: '1:105671027225:android:58fde4fc26dceeb9675888',
    messagingSenderId: '105671027225',
    projectId: 'resume-4e9cc',
    storageBucket: 'resume-4e9cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Ds6EP3gaVag6ixx4I8YmoUmrEKwudx0',
    appId: '1:105671027225:ios:a9ab2af698b8699d675888',
    messagingSenderId: '105671027225',
    projectId: 'resume-4e9cc',
    storageBucket: 'resume-4e9cc.firebasestorage.app',
    iosBundleId: 'com.example.resumeScreening',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Ds6EP3gaVag6ixx4I8YmoUmrEKwudx0',
    appId: '1:105671027225:ios:a9ab2af698b8699d675888',
    messagingSenderId: '105671027225',
    projectId: 'resume-4e9cc',
    storageBucket: 'resume-4e9cc.firebasestorage.app',
    iosBundleId: 'com.example.resumeScreening',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC-Ousti2_JGmiCVNRQXs4pqU1CA6aumE',
    appId: '1:105671027225:web:699871f26c97713f675888',
    messagingSenderId: '105671027225',
    projectId: 'resume-4e9cc',
    authDomain: 'resume-4e9cc.firebaseapp.com',
    storageBucket: 'resume-4e9cc.firebasestorage.app',
    measurementId: 'G-XV98M82QQE',
  );
}
